# Generated by Django 5.0.3 on 2026-04-23 04:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officers', '0001_initial'),
        ('positions', '0001_initial'),
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAssignment',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('date_assumed', models.DateField()),
                ('date_relinquished', models.DateField(blank=True, help_text='NULL means current assignment', null=True)),
                ('assignment_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('ACTING', 'Acting'), ('TEMPORARY', 'Temporary'), ('DETAILED', 'Detailed'), ('DS', 'DS (Detail to Other Unit)')], default='PERMANENT', max_length=20)),
                ('is_promotion_point_eligible', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='officers.officer')),
                ('position', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='positions.position')),
                ('unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='units.unit')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Assignment',
                'verbose_name_plural': 'historical Assignments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_assumed', models.DateField()),
                ('date_relinquished', models.DateField(blank=True, help_text='NULL means current assignment', null=True)),
                ('assignment_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('ACTING', 'Acting'), ('TEMPORARY', 'Temporary'), ('DETAILED', 'Detailed'), ('DS', 'DS (Detail to Other Unit)')], default='PERMANENT', max_length=20)),
                ('is_promotion_point_eligible', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='officers.officer')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='positions.position')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='units.unit')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assignment',
                'verbose_name_plural': 'Assignments',
                'db_table': 'assignments',
                'ordering': ['-date_assumed'],
                'indexes': [models.Index(fields=['officer', '-date_assumed'], name='assignments_officer_408e8b_idx'), models.Index(fields=['unit', 'date_assumed'], name='assignments_unit_id_26c2b7_idx'), models.Index(fields=['date_assumed', 'date_relinquished'], name='assignments_date_as_27296a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(check=models.Q(('date_relinquished__isnull', True), ('date_relinquished__gte', models.F('date_assumed')), _connector='OR'), name='relinquished_after_assumed'),
        ),
    ]
