# Generated by Django 5.0.3 on 2026-04-23 04:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOfficer',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('paf_number', models.CharField(blank=True, db_index=True, help_text='PAF O-number like O-135535', max_length=50, null=True)),
                ('rank', models.CharField(choices=[('LTC', 'Lieutenant Colonel'), ('MAJ', 'Major'), ('CPT', 'Captain'), ('1LT', '1st Lieutenant'), ('2LT', '2nd Lieutenant'), ('CDR', 'Commander'), ('LTCDR', 'Lieutenant Commander'), ('LT', 'Lieutenant'), ('LTJG', 'Lieutenant Junior Grade'), ('ENS', 'Ensign')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('suffix', models.CharField(blank=True, help_text='Jr., Sr., III, etc.', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETIRED', 'Retired'), ('DECEASED', 'Deceased'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('date_commissioned', models.DateField(blank=True, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Officer',
                'verbose_name_plural': 'historical Officers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('paf_number', models.CharField(blank=True, help_text='PAF O-number like O-135535', max_length=50, null=True, unique=True)),
                ('rank', models.CharField(choices=[('LTC', 'Lieutenant Colonel'), ('MAJ', 'Major'), ('CPT', 'Captain'), ('1LT', '1st Lieutenant'), ('2LT', '2nd Lieutenant'), ('CDR', 'Commander'), ('LTCDR', 'Lieutenant Commander'), ('LT', 'Lieutenant'), ('LTJG', 'Lieutenant Junior Grade'), ('ENS', 'Ensign')], max_length=20)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('suffix', models.CharField(blank=True, help_text='Jr., Sr., III, etc.', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('RETIRED', 'Retired'), ('DECEASED', 'Deceased'), ('ON_LEAVE', 'On Leave'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('date_commissioned', models.DateField(blank=True, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Officer',
                'verbose_name_plural': 'Officers',
                'db_table': 'officers',
                'ordering': ['rank', 'last_name', 'first_name'],
                'indexes': [models.Index(fields=['paf_number'], name='officers_paf_num_c2f0c9_idx'), models.Index(fields=['rank', 'status'], name='officers_rank_569e69_idx'), models.Index(fields=['last_name', 'first_name'], name='officers_last_na_61fc16_idx')],
            },
        ),
    ]
