# Generated by Django 5.0.3 on 2026-04-23 04:53

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AircraftType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aircraft_code', models.CharField(help_text='e.g., AW-109, T-129, A-29B, SF-260TP', max_length=20, unique=True)),
                ('aircraft_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('FIXED_WING', 'Fixed Wing'), ('ROTARY_WING', 'Rotary Wing'), ('UAV', 'Unmanned Aerial Vehicle')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Aircraft Type',
                'verbose_name_plural': 'Aircraft Types',
                'db_table': 'aircraft_types',
                'ordering': ['aircraft_code'],
            },
        ),
        migrations.CreateModel(
            name='FlightType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_type_code', models.CharField(max_length=20, unique=True)),
                ('flight_type_name', models.CharField(max_length=50)),
                ('is_night', models.BooleanField(default=False)),
                ('is_instrument', models.BooleanField(default=False)),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='Hour multiplier for this flight type', max_digits=3)),
            ],
            options={
                'verbose_name': 'Flight Type',
                'verbose_name_plural': 'Flight Types',
                'db_table': 'flight_types',
            },
        ),
        migrations.CreateModel(
            name='MissionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mission_code', models.CharField(max_length=30, unique=True)),
                ('mission_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('TRAINING', 'Training'), ('COMBAT', 'Combat'), ('TRANSPORT', 'Transport'), ('PATROL', 'Patrol'), ('RECONNAISSANCE', 'Reconnaissance'), ('SEARCH_RESCUE', 'Search and Rescue'), ('MEDEVAC', 'Medical Evacuation')], max_length=20)),
            ],
            options={
                'verbose_name': 'Mission Type',
                'verbose_name_plural': 'Mission Types',
                'db_table': 'mission_types',
            },
        ),
        migrations.CreateModel(
            name='FlightSummary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total_flight_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_night_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_instrument_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_simulator_hours', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_flights', models.IntegerField(default=0)),
                ('total_night_flights', models.IntegerField(default=0)),
                ('total_instrument_flights', models.IntegerField(default=0)),
                ('last_flight_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flight_summary', to='officers.officer')),
            ],
            options={
                'verbose_name': 'Flight Summary',
                'verbose_name_plural': 'Flight Summaries',
                'db_table': 'flight_summaries',
            },
        ),
        migrations.CreateModel(
            name='HistoricalFlightLog',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('flight_date', models.DateField()),
                ('flight_hours', models.DecimalField(decimal_places=2, help_text='Flight duration in hours (e.g., 2.5 for 2 hours 30 minutes)', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(24.0)])),
                ('sortie_number', models.CharField(blank=True, help_text='Mission sortie number', max_length=20)),
                ('takeoff_time', models.TimeField(blank=True, null=True)),
                ('landing_time', models.TimeField(blank=True, null=True)),
                ('is_night_flight', models.BooleanField(default=False)),
                ('is_instrument_flight', models.BooleanField(default=False)),
                ('is_simulator', models.BooleanField(default=False, help_text='If this was simulator time')),
                ('passenger_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cargo_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('aircraft', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flight_logs.aircrafttype')),
                ('certifying_officer', models.ForeignKey(blank=True, db_constraint=False, help_text='Instructor/Officer who certified this flight', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='officers.officer')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('flight_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flight_logs.flighttype')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='officers.officer')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('mission_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='flight_logs.missiontype')),
            ],
            options={
                'verbose_name': 'historical Flight Log',
                'verbose_name_plural': 'historical Flight Logs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FlightLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_date', models.DateField()),
                ('flight_hours', models.DecimalField(decimal_places=2, help_text='Flight duration in hours (e.g., 2.5 for 2 hours 30 minutes)', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(24.0)])),
                ('sortie_number', models.CharField(blank=True, help_text='Mission sortie number', max_length=20)),
                ('takeoff_time', models.TimeField(blank=True, null=True)),
                ('landing_time', models.TimeField(blank=True, null=True)),
                ('is_night_flight', models.BooleanField(default=False)),
                ('is_instrument_flight', models.BooleanField(default=False)),
                ('is_simulator', models.BooleanField(default=False, help_text='If this was simulator time')),
                ('passenger_count', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('cargo_weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flight_logs', to='flight_logs.aircrafttype')),
                ('certifying_officer', models.ForeignKey(blank=True, help_text='Instructor/Officer who certified this flight', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='certified_flights', to='officers.officer')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_logs', to='officers.officer')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('flight_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flight_logs', to='flight_logs.flighttype')),
                ('mission_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flight_logs', to='flight_logs.missiontype')),
            ],
            options={
                'verbose_name': 'Flight Log',
                'verbose_name_plural': 'Flight Logs',
                'db_table': 'flight_logs',
                'ordering': ['-flight_date'],
                'indexes': [models.Index(fields=['officer', '-flight_date'], name='flight_logs_officer_f7db5e_idx'), models.Index(fields=['flight_date'], name='flight_logs_flight__f11590_idx'), models.Index(fields=['aircraft'], name='flight_logs_aircraf_560559_idx'), models.Index(fields=['flight_type'], name='flight_logs_flight__3b08f1_idx'), models.Index(fields=['mission_type'], name='flight_logs_mission_6f346a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='flightlog',
            constraint=models.CheckConstraint(check=models.Q(('flight_hours__gte', 0.01)), name='flight_hours_positive'),
        ),
    ]
