# Generated by Django 5.0.3 on 2026-05-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flightlog',
            name='aircraft',
        ),
        migrations.RemoveField(
            model_name='historicalflightlog',
            name='aircraft',
        ),
        migrations.RemoveField(
            model_name='flightsummary',
            name='officer',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='flight_type',
        ),
        migrations.RemoveField(
            model_name='historicalflightlog',
            name='flight_type',
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='mission_type',
            field=models.CharField(choices=[('TRAINING', 'Training'), ('COMBAT', 'Combat'), ('RECON', 'Reconnaissance'), ('TRANSPORT', 'Transport'), ('TEST', 'Test Flight'), ('MAINTENANCE', 'Maintenance Flight'), ('OTHER', 'Other')], default='TRAINING', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalflightlog',
            name='mission_type',
            field=models.CharField(choices=[('TRAINING', 'Training'), ('COMBAT', 'Combat'), ('RECON', 'Reconnaissance'), ('TRANSPORT', 'Transport'), ('TEST', 'Test Flight'), ('MAINTENANCE', 'Maintenance Flight'), ('OTHER', 'Other')], default='TRAINING', max_length=20),
        ),
        migrations.AlterModelOptions(
            name='flightlog',
            options={'ordering': ['-flight_date']},
        ),
        migrations.AlterModelOptions(
            name='historicalflightlog',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical flight log', 'verbose_name_plural': 'historical flight logs'},
        ),
        migrations.RemoveConstraint(
            model_name='flightlog',
            name='flight_hours_positive',
        ),
        migrations.RemoveIndex(
            model_name='flightlog',
            name='flight_logs_officer_f7db5e_idx',
        ),
        migrations.RemoveIndex(
            model_name='flightlog',
            name='flight_logs_flight__f11590_idx',
        ),
        migrations.RemoveIndex(
            model_name='flightlog',
            name='flight_logs_aircraf_560559_idx',
        ),
        migrations.RemoveIndex(
            model_name='flightlog',
            name='flight_logs_flight__3b08f1_idx',
        ),
        migrations.RemoveIndex(
            model_name='flightlog',
            name='flight_logs_mission_6f346a_idx',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='cargo_weight_kg',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='certifying_officer',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='is_instrument_flight',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='is_night_flight',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='is_simulator',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='landing_time',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='passenger_count',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='sortie_number',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='takeoff_time',
        ),
        migrations.RemoveField(
            model_name='flightlog',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalflightlog',
            name='cargo_weight_kg',
        ),
        migrations.RemoveField(
            model_name='historicalflightlog',
            name='certifying_officer',
        ),
        migrations.RemoveField(
            model_name='historicalflightlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalflightlog',
            name='is_instrument_flight',
        ),
        migrations.RemoveField(
            model_name='historicalflightlog',
            name='is_night_flight',
        ),
        migrations.RemoveField(
            model_name='historicalflightlog',
            name='is_simulator',
        ),
        migrations.RemoveField(
            model_name='historicalflightlog',
            name='landing_time',
        ),
        migrations.RemoveField(
            model_name='historicalflightlog',
            name='passenger_count',
        ),
        migrations.RemoveField(
            model_name='historicalflightlog',
            name='sortie_number',
        ),
        migrations.RemoveField(
            model_name='historicalflightlog',
            name='takeoff_time',
        ),
        migrations.RemoveField(
            model_name='historicalflightlog',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='flightlog',
            name='aircraft_type',
            field=models.CharField(choices=[('T-129', 'T-129 ATAK'), ('AW-109', 'AW-109AH'), ('MD-520', 'MD-520MG'), ('SF-260', 'SF-260TP'), ('OV-10', 'OV-10 Bronco')], default='T-129', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalflightlog',
            name='aircraft_type',
            field=models.CharField(choices=[('T-129', 'T-129 ATAK'), ('AW-109', 'AW-109AH'), ('MD-520', 'MD-520MG'), ('SF-260', 'SF-260TP'), ('OV-10', 'OV-10 Bronco')], default='T-129', max_length=20),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='flight_hours',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='flightlog',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalflightlog',
            name='flight_hours',
            field=models.DecimalField(decimal_places=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='historicalflightlog',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='AircraftType',
        ),
        migrations.DeleteModel(
            name='FlightSummary',
        ),
        migrations.DeleteModel(
            name='FlightType',
        ),
        migrations.DeleteModel(
            name='MissionType',
        ),
    ]
