# Generated by Django 5.0.3 on 2026-04-23 04:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('officers', '0001_initial'),
        ('positions', '0001_initial'),
        ('units', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSuccessionPlan',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('priority', models.IntegerField(choices=[(1, 'Highest Priority'), (2, 'High Priority'), (3, 'Medium Priority'), (4, 'Low Priority'), (5, 'Lowest Priority')], default=3)),
                ('target_date', models.DateField(blank=True, help_text='Target date for transition', null=True)),
                ('expected_relinquish_date', models.DateField(blank=True, help_text='When current officer is expected to leave', null=True)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='PROPOSED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('proposed_date', models.DateField(blank=True, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('approved_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('current_officer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='officers.officer')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='positions.position')),
                ('proposed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposed_officer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='officers.officer')),
                ('unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='units.unit')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Succession Plan',
                'verbose_name_plural': 'historical Succession Plans',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SuccessionPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('priority', models.IntegerField(choices=[(1, 'Highest Priority'), (2, 'High Priority'), (3, 'Medium Priority'), (4, 'Low Priority'), (5, 'Lowest Priority')], default=3)),
                ('target_date', models.DateField(blank=True, help_text='Target date for transition', null=True)),
                ('expected_relinquish_date', models.DateField(blank=True, help_text='When current officer is expected to leave', null=True)),
                ('status', models.CharField(choices=[('PROPOSED', 'Proposed'), ('APPROVED', 'Approved'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='PROPOSED', max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('proposed_date', models.DateField(blank=True, null=True)),
                ('approved_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_successions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('current_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_in_succession', to='officers.officer')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='succession_plans', to='positions.position')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_successions', to=settings.AUTH_USER_MODEL)),
                ('proposed_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_in_succession', to='officers.officer')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='succession_plans', to='units.unit')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Succession Plan',
                'verbose_name_plural': 'Succession Plans',
                'db_table': 'succession_plans',
                'ordering': ['priority', 'target_date'],
            },
        ),
        migrations.CreateModel(
            name='TransitionLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transition_type', models.CharField(choices=[('PROMOTION', 'Promotion'), ('TRANSFER', 'Transfer'), ('RETIREMENT', 'Retirement'), ('ROTATION', 'Rotation'), ('TEMPORARY', 'Temporary Assignment')], max_length=20)),
                ('effective_date', models.DateField()),
                ('order_number', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('from_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_from', to='positions.position')),
                ('from_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_out', to='units.unit')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions', to='officers.officer')),
                ('succession_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transition_logs', to='succession_plan.successionplan')),
                ('to_position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_to', to='positions.position')),
                ('to_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transitions_in', to='units.unit')),
            ],
            options={
                'verbose_name': 'Transition Log',
                'verbose_name_plural': 'Transition Logs',
                'db_table': 'transition_logs',
                'ordering': ['-effective_date'],
            },
        ),
        migrations.AddIndex(
            model_name='successionplan',
            index=models.Index(fields=['unit', 'position'], name='succession__unit_id_f47931_idx'),
        ),
        migrations.AddIndex(
            model_name='successionplan',
            index=models.Index(fields=['status'], name='succession__status_ce89d8_idx'),
        ),
        migrations.AddIndex(
            model_name='successionplan',
            index=models.Index(fields=['target_date'], name='succession__target__fa8083_idx'),
        ),
        migrations.AddIndex(
            model_name='successionplan',
            index=models.Index(fields=['current_officer'], name='succession__current_c7f9e9_idx'),
        ),
        migrations.AddIndex(
            model_name='successionplan',
            index=models.Index(fields=['proposed_officer'], name='succession__propose_bb2aac_idx'),
        ),
    ]
