# Generated by Django 5.0.3 on 2026-04-23 04:53

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flight_logs', '0001_initial'),
        ('officers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QualificationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qualification_code', models.CharField(max_length=50, unique=True)),
                ('qualification_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('COMMAND', 'Command'), ('SENIOR', 'Senior'), ('BASIC', 'Basic'), ('INSTRUCTOR', 'Instructor'), ('SPECIAL', 'Special'), ('RATING', 'Rating')], max_length=20)),
                ('promotion_points_value', models.DecimalField(decimal_places=2, default=0, help_text='Points this qualification gives for promotion', max_digits=5)),
                ('requires_renewal', models.BooleanField(default=False)),
                ('renewal_interval_months', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Qualification Type',
                'verbose_name_plural': 'Qualification Types',
                'db_table': 'qualification_types',
                'ordering': ['qualification_name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalRating',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('rating_level', models.CharField(choices=[('COMMAND', 'Command'), ('SENIOR', 'Senior'), ('BASIC', 'Basic'), ('NVG_CP', 'NVG CP'), ('INSTRUCTOR', 'Instructor'), ('STANDARDIZATION', 'Standardization')], max_length=20)),
                ('date_achieved', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('certified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='officers.officer')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='officers.officer')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Rating',
                'verbose_name_plural': 'historical Ratings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalQualification',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('date_earned', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('date_renewed', models.DateField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_possible_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('issuing_authority', models.CharField(blank=True, max_length=200)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('PENDING', 'Pending')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='officers.officer')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('qualification_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='qualifications.qualificationtype')),
            ],
            options={
                'verbose_name': 'historical Qualification',
                'verbose_name_plural': 'historical Qualifications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating_level', models.CharField(choices=[('COMMAND', 'Command'), ('SENIOR', 'Senior'), ('BASIC', 'Basic'), ('NVG_CP', 'NVG CP'), ('INSTRUCTOR', 'Instructor'), ('STANDARDIZATION', 'Standardization')], max_length=20)),
                ('date_achieved', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certified_ratings', to='officers.officer')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('officer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='officers.officer')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
                'db_table': 'ratings',
            },
        ),
        migrations.CreateModel(
            name='SpecialDuty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('duty_name', models.CharField(max_length=100)),
                ('duty_code', models.CharField(blank=True, max_length=50)),
                ('points_value', models.DecimalField(decimal_places=2, default=2.0, max_digits=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_duties', to='officers.officer')),
            ],
            options={
                'verbose_name': 'Special Duty',
                'verbose_name_plural': 'Special Duties',
                'db_table': 'special_duties',
            },
        ),
        migrations.CreateModel(
            name='InstructorSpecialty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('specialty_name', models.CharField(max_length=100)),
                ('date_qualified', models.DateField()),
                ('is_current', models.BooleanField(default=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aircraft_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flight_logs.aircrafttype')),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_specialties', to='officers.officer')),
            ],
            options={
                'verbose_name': 'Instructor Specialty',
                'verbose_name_plural': 'Instructor Specialties',
                'db_table': 'instructor_specialties',
                'unique_together': {('officer', 'aircraft_type')},
            },
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_earned', models.DateField()),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('date_renewed', models.DateField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_possible_score', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('issuing_authority', models.CharField(blank=True, max_length=200)),
                ('certificate_number', models.CharField(blank=True, max_length=100)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked'), ('PENDING', 'Pending')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qualifications', to='officers.officer')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('qualification_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qualifications', to='qualifications.qualificationtype')),
            ],
            options={
                'verbose_name': 'Qualification',
                'verbose_name_plural': 'Qualifications',
                'db_table': 'qualifications',
                'ordering': ['-date_earned'],
                'indexes': [models.Index(fields=['officer', 'qualification_type'], name='qualificati_officer_f04249_idx'), models.Index(fields=['status'], name='qualificati_status_9c5988_idx'), models.Index(fields=['expiry_date'], name='qualificati_expiry__f82f03_idx')],
            },
        ),
    ]
