# Generated by Django 5.0.3 on 2026-05-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualifications', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrating',
            name='certified_by',
        ),
        migrations.RemoveField(
            model_name='historicalrating',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalrating',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalrating',
            name='officer',
        ),
        migrations.RemoveField(
            model_name='historicalrating',
            name='updated_by',
        ),
        migrations.AlterUniqueTogether(
            name='instructorspecialty',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='instructorspecialty',
            name='aircraft_type',
        ),
        migrations.RemoveField(
            model_name='instructorspecialty',
            name='officer',
        ),
        migrations.AlterField(
            model_name='historicalqualification',
            name='qualification_type',
            field=models.CharField(choices=[('PILOT', 'Pilot'), ('NAVIGATOR', 'Navigator'), ('INSTRUCTOR', 'Instructor'), ('COMMAND', 'Command'), ('STAFF', 'Staff'), ('SPECIAL_OPS', 'Special Operations'), ('MAINTENANCE', 'Maintenance')], max_length=50),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qualification_type',
            field=models.CharField(choices=[('PILOT', 'Pilot'), ('NAVIGATOR', 'Navigator'), ('INSTRUCTOR', 'Instructor'), ('COMMAND', 'Command'), ('STAFF', 'Staff'), ('SPECIAL_OPS', 'Special Operations'), ('MAINTENANCE', 'Maintenance')], max_length=50),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='certified_by',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='officer',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='specialduty',
            name='officer',
        ),
        migrations.AlterModelOptions(
            name='historicalqualification',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical qualification', 'verbose_name_plural': 'historical qualifications'},
        ),
        migrations.AlterModelOptions(
            name='qualification',
            options={'ordering': ['-date_earned']},
        ),
        migrations.RemoveIndex(
            model_name='qualification',
            name='qualificati_officer_f04249_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualification',
            name='qualificati_status_9c5988_idx',
        ),
        migrations.RemoveIndex(
            model_name='qualification',
            name='qualificati_expiry__f82f03_idx',
        ),
        migrations.RemoveField(
            model_name='historicalqualification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalqualification',
            name='date_renewed',
        ),
        migrations.RemoveField(
            model_name='historicalqualification',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='historicalqualification',
            name='max_possible_score',
        ),
        migrations.RemoveField(
            model_name='historicalqualification',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='historicalqualification',
            name='score',
        ),
        migrations.RemoveField(
            model_name='historicalqualification',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='date_renewed',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='expiry_date',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='max_possible_score',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='score',
        ),
        migrations.RemoveField(
            model_name='qualification',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='historicalqualification',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='historicalqualification',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalqualification',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='qualification',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='qualification',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qualification',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='historicalqualification',
            name='date_earned',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='historicalqualification',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalqualification',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='date_earned',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('REVOKED', 'Revoked')], default='ACTIVE', max_length=20),
        ),
        migrations.DeleteModel(
            name='HistoricalRating',
        ),
        migrations.DeleteModel(
            name='InstructorSpecialty',
        ),
        migrations.DeleteModel(
            name='QualificationType',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
        migrations.DeleteModel(
            name='SpecialDuty',
        ),
    ]
