# Generated by Django 5.0.3 on 2026-04-23 04:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPosition',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('position_code', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('position_title', models.CharField(max_length=200)),
                ('rank_authorized', models.CharField(blank=True, help_text='What rank typically holds this position', max_length=20)),
                ('position_category', models.CharField(blank=True, choices=[('COMMAND', 'Command'), ('STAFF', 'Staff'), ('OPERATIONS', 'Operations'), ('INSTRUCTOR', 'Instructor'), ('SPECIAL_DUTY', 'Special Duty'), ('SUPPORT', 'Support')], max_length=20, null=True)),
                ('promotion_points_value', models.DecimalField(decimal_places=2, default=0, help_text='Points this position gives for promotion', max_digits=5)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Position',
                'verbose_name_plural': 'historical Positions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position_code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('position_title', models.CharField(max_length=200)),
                ('rank_authorized', models.CharField(blank=True, help_text='What rank typically holds this position', max_length=20)),
                ('position_category', models.CharField(blank=True, choices=[('COMMAND', 'Command'), ('STAFF', 'Staff'), ('OPERATIONS', 'Operations'), ('INSTRUCTOR', 'Instructor'), ('SPECIAL_DUTY', 'Special Duty'), ('SUPPORT', 'Support')], max_length=20, null=True)),
                ('promotion_points_value', models.DecimalField(decimal_places=2, default=0, help_text='Points this position gives for promotion', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'db_table': 'positions',
                'ordering': ['position_title'],
                'indexes': [models.Index(fields=['position_title'], name='positions_positio_e08428_idx'), models.Index(fields=['position_category'], name='positions_positio_6b954c_idx')],
            },
        ),
    ]
