# Generated by Django 5.0.3 on 2026-05-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalposition',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical position', 'verbose_name_plural': 'historical positions'},
        ),
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['position_title']},
        ),
        migrations.RemoveIndex(
            model_name='position',
            name='positions_positio_e08428_idx',
        ),
        migrations.RemoveIndex(
            model_name='position',
            name='positions_positio_6b954c_idx',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='promotion_points_value',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='rank_authorized',
        ),
        migrations.RemoveField(
            model_name='historicalposition',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='position',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='position',
            name='promotion_points_value',
        ),
        migrations.RemoveField(
            model_name='position',
            name='rank_authorized',
        ),
        migrations.RemoveField(
            model_name='position',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='historicalposition',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalposition',
            name='position_category',
            field=models.CharField(choices=[('COMMAND', 'Command'), ('STAFF', 'Staff'), ('OPERATIONS', 'Operations'), ('SUPPORT', 'Support'), ('TRAINING', 'Training')], default='STAFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalposition',
            name='position_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_category',
            field=models.CharField(choices=[('COMMAND', 'Command'), ('STAFF', 'Staff'), ('OPERATIONS', 'Operations'), ('SUPPORT', 'Support'), ('TRAINING', 'Training')], default='STAFF', max_length=20),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
