# Generated by Django 5.0.3 on 2026-04-23 04:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('unit_code', models.CharField(help_text='e.g., 460AMG, 16AS, HAS', max_length=20, unique=True)),
                ('unit_name', models.CharField(blank=True, max_length=200)),
                ('unit_type', models.CharField(blank=True, choices=[('WING', 'Wing'), ('GROUP', 'Group'), ('SQUADRON', 'Squadron'), ('HEADQUARTERS', 'Headquarters'), ('SUPPORT', 'Support Unit'), ('TRAINING', 'Training Unit')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subunits', to='units.unit')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'db_table': 'units',
                'ordering': ['unit_code'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalUnit',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('unit_code', models.CharField(db_index=True, help_text='e.g., 460AMG, 16AS, HAS', max_length=20)),
                ('unit_name', models.CharField(blank=True, max_length=200)),
                ('unit_type', models.CharField(blank=True, choices=[('WING', 'Wing'), ('GROUP', 'Group'), ('SQUADRON', 'Squadron'), ('HEADQUARTERS', 'Headquarters'), ('SUPPORT', 'Support Unit'), ('TRAINING', 'Training Unit')], max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('parent_unit', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='units.unit')),
            ],
            options={
                'verbose_name': 'historical Unit',
                'verbose_name_plural': 'historical Units',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['unit_code'], name='units_unit_co_7e3dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['unit_type'], name='units_unit_ty_9d1e44_idx'),
        ),
    ]
