# Generated by Django 5.0.3 on 2026-05-05 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalunit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical unit', 'verbose_name_plural': 'historical units'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['unit_code']},
        ),
        migrations.RemoveIndex(
            model_name='unit',
            name='units_unit_co_7e3dd8_idx',
        ),
        migrations.RemoveIndex(
            model_name='unit',
            name='units_unit_ty_9d1e44_idx',
        ),
        migrations.RemoveField(
            model_name='historicalunit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalunit',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='historicalunit',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='historicalunit',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='unit_type',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='id',
            field=models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='unit_code',
            field=models.CharField(db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalunit',
            name='unit_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='parent_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_name',
            field=models.CharField(max_length=200),
        ),
    ]
